name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.3'
          extended: true

      - name: Use Node 13
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          git config --global core.quotePath false
          hugo --gc --minify --cleanDestinationDir
          gulp build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOY_KEY }}
          EXTERNAL_REPOSITORY: FFRaycoder/ffraycoder.github.io
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
          commit_message: ${{ github.event.head_commit.message }}
         